### ISSUE TITLE
Intermittent CI failure with build-ckzg-dotnet

### ISSUE THREAD

**Issue by jtraglia** [ethereum/c-kzg-4844#239]
Every so often, the `build-ckzg-dotnet` CI action will fail with this error:

> System.Exception: Unable to read beyond the end of the stream.

He's an instance of this error:

https://github.com/ethereum/c-kzg-4844/actions/runs/4485648662/jobs/7887434752?pr=238

Here's the full output:

```
  cd bindings/csharp && dotnet test -c release --no-restore
  shell: /usr/bin/bash -e {0}
  env:
    binding_build_number_based_version: 0.1.2.108
/home/runner/.nuget/packages/microsoft.build.tasks.git/1.1.1/build/Microsoft.Build.Tasks.Git.targets(25,5): warning : Could not find file '/home/runner/work/c-kzg-4844/c-kzg-4844/blst/.git'. The source code won't be available via Source Link. [/home/runner/work/c-kzg-4844/c-kzg-4844/bindings/csharp/Ckzg.Bindings/Ckzg.Bindings.csproj]
  Ckzg.Bindings -> /home/runner/work/c-kzg-4844/c-kzg-4844/bindings/csharp/Ckzg.Bindings/bin/Release/net6.0/Ckzg.Bindings.dll
  Ckzg.Test -> /home/runner/work/c-kzg-4844/c-kzg-4844/bindings/csharp/Ckzg.Test/bin/Release/net7.0/Ckzg.Test.dll
Test run for /home/runner/work/c-kzg-4844/c-kzg-4844/bindings/csharp/Ckzg.Test/bin/Release/net7.0/Ckzg.Test.dll (.NETCoreApp,Version=v7.0)
Microsoft (R) Test Execution Command Line Tool Version 17.5.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
The active test run was aborted. Reason: Test host process crashed

Test Run Aborted with error System.Exception: One or more errors occurred.
 ---> System.Exception: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---.
```

**Comment by jtraglia** [comment]
@flcl42 have you experienced this before?

**Comment by flcl42** [comment]
@jtraglia yes, it may be caused by different problems. I'm checking what is the issue in this particular case.

**Comment by asn-d6** [comment]
Hmm, any news here? This is triggering relatively often.

**Comment by jtraglia** [comment]
@flcl42 any updates?

**Comment by asn-d6** [comment]
Another case of broken CI: https://github.com/ethereum/c-kzg-4844/actions/runs/4935167135

**Comment by jtraglia** [comment]
I'm thinking this may be the blst's SIGILL problem in disguise. I'm going to make a PR that forces all of the CI tests to use the portable version of blst and see if it fixes the issue.

**Comment by jtraglia** [comment]
Haven't seen this issue in a while. I think it's been fixed.
